//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Plugin.Messaging")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("4.0.0.7")]
[assembly: AssemblyInformationalVersion("4.0.0")]
[assembly: AssemblyCopyright("Copyright (c) 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("RELEASE")]

