#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Plugin.Messaging.Sample.Android.Resource", IsApplication=true)]

namespace Plugin.Messaging.Sample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int ButtonMakePhoneCall = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ButtonMakePhoneCallAutoDial = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int ButtonSendAttachmentEmail = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ButtonSendAttachmentEmailPCL = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int ButtonSendBackgroundSms = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ButtonSendEmail = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ButtonSendEmailStrictMode = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ButtonSendHtmlEmail = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int ButtonSendMultipleSms = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ButtonSendSms = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int file_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
